from object_detector.ssd.protos import string_int_label_map_pb2
from object_detector.ssd.ssd_object_detector import SSDObjectDetector
from .mask_rcnn.mask_rcnn_object_detector import MaskRCNNObjectDetector
from .yolo.yolo_object_detector import YOLOObjectDetector
